-- MySQL Script generated by MySQL Workbench
-- Mon Jan 19 12:54:28 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema ai
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ai` ;

-- -----------------------------------------------------
-- Schema ai
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ai` ;
USE `ai` ;

-- -----------------------------------------------------
-- Table `ai`.`Admin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ai`.`Admin` ;

CREATE TABLE IF NOT EXISTS `ai`.`Admin` (
  `idAdmin` INT(11) NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `wachtwoord` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idAdmin`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ai`.`vraag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ai`.`vraag` ;

CREATE TABLE IF NOT EXISTS `ai`.`vraag` (
  `idvraag` INT(11) NOT NULL AUTO_INCREMENT,
  `vraag` VARCHAR(255) NULL DEFAULT NULL,
  `antwoord` VARCHAR(255) NULL DEFAULT NULL,
  `beantwoord` TINYINT(1) NULL DEFAULT NULL,
  `keywoord` VARCHAR(45) NULL,
  PRIMARY KEY (`idvraag`))
ENGINE = InnoDB
AUTO_INCREMENT = 6;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
